# Generated by Django 5.0 on 2023-12-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(null=True, upload_to="uploaded_files/")),
                ("unique_name", models.CharField(max_length=255, unique=True)),
                ("original_name", models.CharField(max_length=255)),
                ("s3_url", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
