# Generated by Django 5.0 on 2023-12-10 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="uploadedfile",
            options={
                "verbose_name": "Uploaded File",
                "verbose_name_plural": "Uploaded Files",
            },
        ),
    ]
